[package]
name = "simple_cex_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
hex = "0.4.3"
hmac = "0.12.1"
log = "0.4.27"
reqwest = "0.12.22"
serde_json = "1.0.140"
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["full"] }
url = "2.5.4"
